// src/components/section.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    variant?: "primary" | "secondary" | "surface" | "inactive";
    children: Snippet;
  }

  let { children, variant = "primary" }: Props = $props();

  const className = $derived(`background-${variant}`);
</script>

<section class={className}>{@render children()}</section>

<style>
  section {
    display: flex;
    flex-direction: column;
    row-gap: 1em;
    margin-bottom: 1em;
    padding: 1em;
    border-radius: var(--border-radius);
  }

  .background-primary {
    background-color: var(--primary-800);
  }

  .background-secondary {
    background-color: var(--secondary-800);
  }

  .background-surface {
    background-color: var(--surface-800);
  }

  .background-inactive {
    background-color: var(--surface-400);
  }
</style>

// packages/app/src/components/Section.tsx
import type { FlowComponent } from 'solid-js';

export enum SectionVariant {
  PRIMARY = 0,
  SECONDARY = 1,
  SURFACE = 2,
  INACTIVE = 3,
}

export interface Props {
  variant?: SectionVariant;
}

export const Section: FlowComponent<Props> = ({ variant = SectionVariant.PRIMARY, children }) => (
  <section class={`flex flex-col gap-y-4 p-4 rounded-lg ${BACKGROUND_COLOR[variant]}`}>{children}</section>
);

const BACKGROUND_COLOR: Record<SectionVariant, string> = {
  [SectionVariant.PRIMARY]: 'bg-primary-800',
  [SectionVariant.SECONDARY]: 'bg-secondary-800',
  [SectionVariant.SURFACE]: 'bg-surface-800',
  [SectionVariant.INACTIVE]: 'bg-surface-400',
};
