// src/components/nordnet/nordnet-section.svelte
<script lang="ts">
  import Heading from "@app/components/heading.svelte";
  import Table from "@app/components/table.svelte";
  import Section from "@app/components/section.svelte";
  import type { Csv } from "@app/lib/csv";
  import CsvIcon from "virtual:icons/mdi/file-csv";
  import ExpandIcon from "virtual:icons/mdi/expand-more";
  import CollapseIcon from "virtual:icons/mdi/expand-less";
  import DeleteIcon from "virtual:icons/mdi/delete";
  import NordnetRow from "@app/components/nordnet/nordnet-row.svelte";

  interface Props {
    fileName: string;
    data: Csv;
    onDelete: () => void;
  }

  let { fileName, data, onDelete }: Props = $props();

  let isOpen = $state(false);

  const headers = data.headers;
  const rows = data.rows;

  const onclick = () => {
    isOpen = !isOpen;
  };
</script>

<Section variant={rows.length === 0 ? "inactive" : "surface"}>
  <Heading level={1} size="xsmall">
    <button {onclick} class="expand">
      {#if isOpen}
        <CollapseIcon />
      {:else}
        <ExpandIcon />
      {/if}
      <CsvIcon />
      <span>{fileName} ({rows.length} linjer)</span>
    </button>
    <button class="delete" onclick={onDelete}>
      <DeleteIcon />
    </button>
  </Heading>

  {#if isOpen}
    {#if rows.length === 0}
      <p><em>Ingen transaksjoner</em></p>
    {:else}
      <Table {headers} rowCount={rows.length} showLineNumbers>
        {#each rows as line, lineNumber}
          <NordnetRow {line} {lineNumber} />
        {/each}
      </Table>
    {/if}
  {/if}
</Section>

<style>
  button {
    display: flex;
    align-items: center;
    align-content: center;
    justify-content: left;
    column-gap: 4px;
    background: none;
    border: none;
    cursor: pointer;
    font-size: inherit;
    font-family: inherit;
    color: inherit;
    text-align: inherit;
    padding: 0;
  }

  .expand {
    flex-grow: 1;
  }

  .delete {
    flex-grow: 0;
    flex-shrink: 0;
    color: red;
  }
</style>

// src/components/Nordnet/NordnetSection.tsx
import { Heading, HeadingSize } from '@app/components/Heading';
import { NordnetRow } from '@app/components/Nordnet/NordnetRow';
import { Section, SectionVariant } from '@app/components/Section';
import { Table } from '@app/components/Table';
import type { Csv } from '@app/lib/csv';
import { Index, Show, type VoidComponent, createSignal } from 'solid-js';
import { styled } from 'solid-styled-components';
import DeleteIcon from '~icons/mdi/Delete';
import ExpandLessIcon from '~icons/mdi/ExpandLess';
import ExpandMore from '~icons/mdi/ExpandMore';
import CsvIcon from '~icons/mdi/FileCsv';

interface Props {
  fileName: string;
  data: Csv;
  onDelete: () => void;
}

export const NordnetSection: VoidComponent<Props> = ({ fileName, data, onDelete }) => {
  const [isOpen, setIsOpen] = createSignal(false);

  const { headers, rows } = data;
  const rowCount = rows.length;

  return (
    <Section variant={rows.length === 0 ? SectionVariant.INACTIVE : SectionVariant.SURFACE}>
      <Heading level={1} size={HeadingSize.XSMALL}>
        <ExpandButton onClick={() => setIsOpen((o) => !o)}>
          {isOpen() ? <ExpandLessIcon /> : <ExpandMore />}
          <CsvIcon />
          <span>
            {fileName} ({rows.length} linjer)
          </span>
        </ExpandButton>
        <DeleteButton onClick={onDelete}>
          <DeleteIcon />
        </DeleteButton>
      </Heading>
      <Show when={isOpen()}>
        <Show when={rowCount !== 0} fallback={<NoTransactions />}>
          <Table headers={headers} rowCount={rowCount} showLineNumbers>
            <Index each={rows}>{(line, index) => <NordnetRow line={line} lineNumber={index} />}</Index>
          </Table>
        </Show>
      </Show>
    </Section>
  );
};

const NoTransactions: VoidComponent = () => (
  <p>
    <em>Ingen transaksjoner</em>
  </p>
);

const HeadingButton = styled.button`
  display: flex;
  align-items: center;
  align-content: center;
  justify-content: left;
  column-gap: 4px;
  background: none;
  border: none;
  cursor: pointer;
  font-size: inherit;
  font-family: inherit;
  color: inherit;
  text-align: inherit;
  padding: 0;
`;

const ExpandButton = styled(HeadingButton)`
  flex-grow: 1;
`;

const DeleteButton = styled(HeadingButton)`
  flex-grow: 0;
  flex-shrink: 0;
  color: red;
`;
