// src/components/nordnet/nordnet-row.svelte
<script lang="ts">
  interface Props {
    line: string[];
    lineNumber: number;
  }

  let { line, lineNumber }: Props = $props();
</script>

<tr>
  <td>{lineNumber + 1}</td>
  {#each line as column}
    <td>{column}</td>
  {/each}
</tr>

<style>
  tr {
    &:nth-of-type(odd) {
      background-color: var(--table-odd-row);
    }

    &:nth-of-type(even) {
      background-color: var(--table-even-row);
    }

    &:hover {
      background-color: var(--table-hover-row);
    }
  }

  td {
    padding: 0.5em;
    white-space: nowrap;
  }
</style>

// src/components/Nordnet/NordnetRow.tsx
import { type Accessor, Index, type VoidComponent } from 'solid-js';
import { styled } from 'solid-styled-components';

interface Props {
  line: Accessor<string[]>;
  lineNumber: number;
}

export const NordnetRow: VoidComponent<Props> = ({ line, lineNumber }) => (
  <StyledRow>
    <StyledCell>{lineNumber + 1}</StyledCell>
    <Index each={line()}>{(cell) => <StyledCell>{cell()}</StyledCell>}</Index>
  </StyledRow>
);

const StyledRow = styled.tr`
  &:nth-of-type(odd) {
    background-color: var(--table-odd-row);
  }

  &:nth-of-type(even) {
    background-color: var(--table-even-row);
  }

  &:hover {
    background-color: var(--table-hover-row);
  }
`;

const StyledCell = styled.td`
  padding: 0.5em;
  white-space: nowrap;
`;
