// src/components/modal-button.svelte
<script lang="ts">
  import Button from "@app/components/button.svelte";
  import Modal from "@app/components/modal.svelte";
  import type { Snippet } from "svelte";

  interface Props {
    buttonText: string;
    variant: "primary" | "secondary" | "warning" | "error";
    size?: "small" | "medium" | "large";
    icon?: Snippet;
    defaultOpen?: boolean;
    onClose?: () => void;
    children: Snippet;
  }

  let { buttonText, children, variant, defaultOpen = false, onClose, ...buttonProps }: Props = $props();

  let isOpen = $state<boolean>(defaultOpen);

  const close = () => {
    isOpen = false;
    onClose?.();
  };

  const open = () => {
    isOpen = true;
  };
</script>

<Button {...buttonProps} variant={variant} onclick={open}>
  {buttonText}
</Button>

<Modal variant={variant} isOpen={isOpen} onClose={close}>
  {@render children()}
</Modal>

// src/components/Modal/ModalButton.tsx
import { Button, type ButtonProps, ButtonVariant } from '@app/components/Button';
import { Modal } from '@app/components/Modal/Modal';
import { ModalVariant } from '@app/components/Modal/types';
import { createSignal, type FlowComponent } from 'solid-js';

interface Props extends ButtonProps {
  buttonText: string;
  defaultOpen?: boolean;
  onClose?: () => void;
}

export const ModalButton: FlowComponent<Props> = ({
  buttonText,
  variant = ButtonVariant.PRIMARY,
  size,
  icon,
  defaultOpen = false,
  onClose,
  children,
}) => {
  const [isOpen, setIsOpen] = createSignal(defaultOpen);

  const close = () => {
    setIsOpen(false);
    onClose?.();
  };

  return (
    <>
      <Button variant={variant} size={size} onClick={() => setIsOpen(true)} icon={icon}>
        {buttonText}
      </Button>
      <Modal variant={BUTTON_VARAINT_TO_MODAL_VARIANT[variant]} isOpen={isOpen} onClose={close}>
        {children}
      </Modal>
    </>
  );
};

const BUTTON_VARAINT_TO_MODAL_VARIANT: Record<ButtonVariant, ModalVariant> = {
  [ButtonVariant.PRIMARY]: ModalVariant.PRIMARY,
  [ButtonVariant.SECONDARY]: ModalVariant.SECONDARY,
  [ButtonVariant.WARNING]: ModalVariant.WARNING,
  [ButtonVariant.ERROR]: ModalVariant.ERROR,
};
