// src/components/button.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    variant: "primary" | "secondary" | "warning" | "error";
    size?: "small" | "medium" | "large";
    icon?: Snippet;
    children?: Snippet;
    onclick: HTMLButtonElement["onclick"];
  }

  let { variant = "primary", icon, children, size = "medium", ...attributes }: Props = $props();
</script>

<button {...attributes} class={`${variant} ${size}`}>
  {#if icon !== undefined}
    {@render icon()}
  {/if}
  {#if children !== undefined}
    <span>
      {@render children()}
    </span>
  {/if}
</button>

<style>
  button {
    display: flex;
    align-items: center;
    flex-direction: row;
    border-radius: var(--border-radius);
    border: none;
    color: var(--text-color);
    text-align: center;
    text-decoration: none;
    cursor: pointer;
    font-size: 1rem;
    column-gap: 0.25em;

    &.primary {
      background-color: var(--primary-500);

      &:hover {
        background-color: var(--primary-400);
      }
    }

    &.secondary {
      background-color: var(--secondary-500);

      &:hover {
        background-color: var(--secondary-400);
      }
    }

    &.warning {
      color: var(--text-color-inverted);
      background-color: var(--warning-500);

      &:hover {
        background-color: var(--warning-400);
      }
    }

    &.error {
      background-color: var(--error-500);

      &:hover {
        background-color: var(--error-400);
      }
    }
    

    &.small {
      padding: 0.25em .5em;
    }

    &.medium {
      padding: 0.5em 1em;
      
    }

    &.large {
      padding: 0.75em 1.5em;
    }
  }
</style>

// src/components/Button.tsx
import type { FlowComponent, JSX } from 'solid-js';
import { styled } from 'solid-styled-components';

export enum ButtonVariant {
  PRIMARY = 0,
  SECONDARY = 1,
  WARNING = 2,
  ERROR = 3,
}

export enum ButtonSize {
  SMALL = 0,
  MEDIUM = 1,
  LARGE = 2,
}

export interface ButtonProps {
  variant?: ButtonVariant;
  size?: ButtonSize;
  icon?: JSX.Element;
  onClick?: JSX.EventHandler<HTMLButtonElement, MouseEvent>;
}

export const Button: FlowComponent<ButtonProps> = ({
  variant = ButtonVariant.PRIMARY,
  size = ButtonSize.MEDIUM,
  icon,
  children,
  onClick,
}) => {
  return (
    <StyledButton type="button" onClick={onClick} $variant={variant} $size={size}>
      {icon === undefined ? null : icon}
      <span>{children}</span>
    </StyledButton>
  );
};

interface StyleProps {
  $variant: ButtonVariant;
  $size: ButtonSize;
}

const StyledButton = styled.button<StyleProps>`
  display: flex;
  align-items: center;
  flex-direction: row;
  border-radius: var(--border-radius);
  border: none;
  text-align: center;
  text-decoration: none;
  cursor: pointer;
  font-size: 1rem;
  column-gap: 0.25em;
  
  color: ${({ $variant }) => color($variant)};
  background-color: ${({ $variant }) => backgroundColor($variant)};
  padding: ${({ $size }) => padding($size)};

  &:hover {
    background-color: ${({ $variant }) => hoverBackgroundColor($variant)};
  }
`;

const color = (variant: ButtonVariant) => {
  switch (variant) {
    case ButtonVariant.WARNING:
      return 'var(--text-color-inverted)';
    default:
      return 'var(--text-color)';
  }
};

const backgroundColor = (variant: ButtonVariant) => {
  switch (variant) {
    case ButtonVariant.PRIMARY:
      return 'var(--primary-500)';
    case ButtonVariant.SECONDARY:
      return 'var(--secondary-500)';
    case ButtonVariant.WARNING:
      return 'var(--warning-500)';
    case ButtonVariant.ERROR:
      return 'var(--error-500)';
  }
};

const hoverBackgroundColor = (variant: ButtonVariant) => {
  switch (variant) {
    case ButtonVariant.PRIMARY:
      return 'var(--primary-400)';
    case ButtonVariant.SECONDARY:
      return 'var(--secondary-400)';
    case ButtonVariant.WARNING:
      return 'var(--warning-400)';
    case ButtonVariant.ERROR:
      return 'var(--error-400)';
  }
};

const padding = (size: ButtonSize) => {
  switch (size) {
    case ButtonSize.SMALL:
      return '0.25em 0.5em';
    case ButtonSize.MEDIUM:
      return '0.5em 1em';
    case ButtonSize.LARGE:
      return '0.75em 1.5em';
  }
};
