// src/components/heading.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  
  interface Props {
    level: 1 | 2 | 3 | 4 | 5 | 6;
    size: "xsmall" | "small" | "medium" | "large";
    spacing?: boolean;
    centered?: boolean;
    children: Snippet;
  }

  let { level = 1, size = "medium", spacing = false, centered = false, children }: Props = $props();

  let className = $derived(`heading ${size} ${spacing ? "spacing" : "no-spacing"} ${centered ? "centered" : ""}`);
</script>

{#if level === 1}
  <h1 class={className}>{@render children()}</h1>
{:else if level === 2}
  <h2 class={className}>{@render children()}</h2>
{:else if level === 3}
  <h3 class={className}>{@render children()}</h3>
{:else if level === 4}
  <h4 class={className}>{@render children()}</h4>
{:else if level === 5}
  <h5 class={className}>{@render children()}</h5>
{:else if level === 6}
  <h6 class={className}>{@render children()}</h6>
{/if}

<style>
  .heading {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: left;
    column-gap: 0.25em;
    font-size: 2rem;
    margin-top: 0;
  }

  .spacing {
    margin-bottom: 1em;
  }

  .no-spacing {
    margin-bottom: 0;
  }

  .centered {
    justify-content: center;
  }

  .xsmall {
    font-size: 1rem;
  }

  .small {
    font-size: 1.5rem;
  }

  .medium {
    font-size: 2rem;
  }

  .large {
    font-size: 2.5rem;
  }
</style>

// src/components/Heading.tsx
import type { FlowComponent } from 'solid-js';
import type { JSX } from 'solid-js/jsx-runtime';

export enum HeadingSize {
  XSMALL = -1,
  SMALL = 0,
  MEDIUM = 1,
  LARGE = 2,
}

type HeadingLevel = 1 | 2 | 3 | 4 | 5 | 6;

interface Props {
  level: HeadingLevel;
  size: HeadingSize;
  spacing?: boolean;
  centered?: boolean;
  children: JSX.Element;
}

export const Heading: FlowComponent<Props> = ({
  level,
  size = HeadingSize.MEDIUM,
  spacing = false,
  centered = false,
  children,
}) => {
  const style: JSX.CSSProperties = {
    display: 'flex',
    'flex-direction': 'row',
    'align-items': 'center',
    'column-gap': '0.25em',
    'margin-top': 0,
    'justify-content': centered ? 'center' : 'left',
    'font-size': fontSize(size),
    'margin-bottom': spacing ? '1em' : 0,
  };

  switch (level) {
    case 1:
      return <h1 style={style}>{children}</h1>;
    case 2:
      return <h2 style={style}>{children}</h2>;
    case 3:
      return <h3 style={style}>{children}</h3>;
    case 4:
      return <h4 style={style}>{children}</h4>;
    case 5:
      return <h5 style={style}>{children}</h5>;
    case 6:
      return <h6 style={style}>{children}</h6>;
  }
};

const fontSize = (size: HeadingSize) => {
  switch (size) {
    case HeadingSize.XSMALL:
      return '1rem';
    case HeadingSize.SMALL:
      return '1.5rem';
    case HeadingSize.MEDIUM:
      return '2rem';
    case HeadingSize.LARGE:
      return '2.5rem';
  }
};
