// packages/app/src/components/Input.tsx
import { type Accessor, type JSX, Show, type VoidComponent, createUniqueId } from 'solid-js';

interface InputProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange' | 'class'> {
  label?: JSX.Element;
  description?: JSX.Element;
  value: Accessor<string>;
  onChange: (value: string) => void;
  className?: string;
}

export const Input: VoidComponent<InputProps> = ({
  value,
  onChange,
  className,
  label,
  description,
  id = createUniqueId(),
  ...rest
}) => {
  const descriptionId = description !== undefined ? createUniqueId() : undefined;

  return (
    <div class={className}>
      <Show when={label}>
        <label for={id} class="block font-bold mb-1">
          {label}
        </label>
      </Show>

      <input
        {...rest}
        class={INPUT_CLASSES}
        value={value()}
        onInput={({ currentTarget }) => onChange(currentTarget.value)}
        aria-describedby={description ? descriptionId : undefined}
      />

      <Show when={description}>
        <div id={descriptionId} class="italic text-md mt-2">
          {description}
        </div>
      </Show>
    </div>
  );
};

const INPUT_CLASSES = `
w-full
justify-self-start
leading-none
text-base
text-text-default
rounded-lg
px-1
py-0.5
border
border-surface-500
bg-surface-700
focus:border-primary-500
invalid:border-error-500
focus:outline-none`;

// src/components/input.svelte
<script lang="ts">
  import Section from "./section.svelte";

  interface Props {
    value: string;
    label: string;
    placeholder: string;
    onchange: (value: string) => void;
  }

  const { label, onchange, ...rest }: Props = $props();
</script>

<Section variant="secondary">
  <label for="from_account">{label}</label>
  <input
    id="from_account"
    type="text"
    {...rest}
    onchange={({ currentTarget }) => onchange(currentTarget.value)}
  />
</Section>

<style>
  input {
    justify-self: left;
    width: 20em;
    font-size: 1em;
    color: var(--text-color);
    border-radius: 9999px;
    padding-left: 1em;
    padding-right: 1em;
    padding-top: 0.5em;
    padding-bottom: 0.5em;
    border-style: solid;
    border-width: 1px;
    background-color: var(--surface-700);
    border-color: var(--surface-500);

    &:focus {
      outline: none;
      border-color: var(--primary-500);
    }
  }
</style>
