// packages/app/src/components/Modal/Modal.tsx
import { Button, ButtonSize, ButtonVariant } from '@app/components/Button';
import { Heading, HeadingSize } from '@app/components/Heading';
import { ModalVariant } from '@app/components/Modal/types';
import {
  type Accessor,
  type ComponentProps,
  type FlowComponent,
  type JSX,
  Show,
  createEffect,
  createSignal,
  onCleanup,
} from 'solid-js';
import { twMerge } from 'tailwind-merge';
import CloseIcon from '~icons/mdi/WindowClose';

interface Props {
  isOpen: Accessor<boolean>;
  onClose?: () => void;
  variant?: ModalVariant;
  heading: string;
  icon: (props: ComponentProps<'svg'>) => JSX.Element;
  className?: string;
  actions?: JSX.Element;
  onRef?: (ref: HTMLDialogElement) => void;
}

export const Modal: FlowComponent<Props> = ({
  isOpen,
  onClose,
  variant = ModalVariant.PRIMARY,
  children,
  heading,
  icon: Icon,
  className,
  actions,
  onRef,
}) => {
  let dialogRef: HTMLDialogElement;

  createEffect(() => {
    if (isOpen()) {
      dialogRef.showModal();
    } else {
      dialogRef.close();
    }
  });

  const closeModal = () => {
    dialogRef.close();
    onClose?.();
  };

  const [startX, setStartX] = createSignal(0);
  const [startY, setStartY] = createSignal(0);

  const onMouseDown = (event: MouseEvent) => {
    setStartX(event.clientX);
    setStartY(event.clientY);
  };

  const onClick = (event: MouseEvent) => {
    if (event.target === dialogRef) {
      const { left, right, top, bottom } = dialogRef.getBoundingClientRect();

      if (
        (event.clientX < left || event.clientX > right || event.clientY < top || event.clientY > bottom) &&
        (startX() < left || startX() > right || startY() < top || startY() > bottom)
      ) {
        closeModal();
      }
    }
  };

  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key === 'Escape') {
      closeModal();
    }
  };

  createEffect(() => {
    window.addEventListener('click', onClick);
    window.addEventListener('keydown', onKeyDown);
    window.addEventListener('mousedown', onMouseDown);

    onCleanup(() => {
      window.removeEventListener('click', onClick);
      window.removeEventListener('keydown', onKeyDown);
      window.removeEventListener('mousedown', onMouseDown);
    });
  });

  return (
    <dialog
      class={twMerge(
        `absolute m-auto rounded-lg border-1 ${BORDER_COLOR[variant]} bg-surface-900 not-italic text-base text-text-default max-w-[95%] w-fit backdrop:backdrop-blur-xs backdrop:backdrop-brightness-50 open:flex flex-col`,
        className,
      )}
      ref={(ref) => {
        dialogRef = ref;
        onRef?.(ref);
      }}
      onClose={onClose}
    >
      <header class="flex items-center p-4 bg-surface-800 border-b-1 border-surface-700 shrink-0">
        <Heading level={1} size={HeadingSize.XSMALL}>
          <Icon />
          <span>{heading}</span>
        </Heading>

        <Button
          variant={ButtonVariant.SECONDARY}
          size={ButtonSize.SMALL}
          onClick={closeModal}
          icon={CloseIcon}
          className="ml-auto"
        >
          Lukk
        </Button>
      </header>

      <div class="p-4 grow">{children}</div>

      <Show when={actions}>
        <footer class="flex justify-end p-4 w-full gap-4 shrink-0">{actions}</footer>
      </Show>
    </dialog>
  );
};

const BORDER_COLOR: Record<ModalVariant, string> = {
  [ModalVariant.PRIMARY]: 'border-primary-500',
  [ModalVariant.SECONDARY]: 'border-secondary-500',
  [ModalVariant.WARNING]: 'border-warning-500',
  [ModalVariant.ERROR]: 'border-error-500',
};

// src/components/modal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import Button from "@app/components/button.svelte";
  import CloseIcon from "virtual:icons/mdi/window-close";
  import HelpIcon from "virtual:icons/mdi/help-circle";
  import ErrorIcon from "virtual:icons/mdi/error";
  import WarningIcon from "virtual:icons/mdi/warning";

  interface Props {
    children: Snippet;
    isOpen: boolean;
    onClose?: () => void;
    variant?: "primary" | "secondary" | "warning" | "error";
  }

  let { children, isOpen, onClose, variant = "primary" }: Props = $props();

  let modal: HTMLDialogElement;

  $effect(() => {
    window.addEventListener("keydown", onKeyDown);
    window.addEventListener("click", onClick);
    window.addEventListener("mousedown", onMouseDown);
    
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener("click", onClick);
      window.removeEventListener("mousedown", onMouseDown);
    };
  })

  const close = () => {
    modal.close();
    onClose?.();
  };

  $effect(() => {
    if (isOpen && !modal.open) {
      modal.showModal();
    } else if (modal.open) {
      close();
    }
  });

  let startX = 0;
  let startY = 0;

  const onMouseDown = (event: MouseEvent) => {
    startX = event.clientX;
    startY = event.clientY;
  };

  const onClick = (event: MouseEvent) => {
    if (event.target === modal) {
      const { left, right, top, bottom } = modal.getBoundingClientRect();
      
      if (
        (event.clientX < left || event.clientX > right || event.clientY < top || event.clientY > bottom) && 
        (startX < left || startX > right || startY < top || startY > bottom)
      ) {
        close();
      }
    }
  };

  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key === "Escape") {
      close();
    }
  };
</script>

<dialog bind:this={modal} class={variant}>
  <section class="modal-content">
    <h1 class="heading">
      {#if variant === "primary"}
        {@render helpIcon()} Info
      {:else if variant === "secondary"}
        {@render helpIcon()} Info
      {:else if variant === "warning"}
        {@render warningIcon()} Advarsel
      {:else if variant === "error"}
        {@render errorIcon()} Feil
      {/if}
    </h1>

    {@render children()}
    
  </section>
  <footer>
    <Button variant="secondary" size="small" onclick={close} icon={closeIcon}>
      Lukk
    </Button>
  </footer>
</dialog>

{#snippet closeIcon()}
  <CloseIcon />
{/snippet}

{#snippet helpIcon()}
  <HelpIcon />
{/snippet}

{#snippet warningIcon()}
  <WarningIcon />
{/snippet}

{#snippet errorIcon()}
  <ErrorIcon />
{/snippet}

<style>
  dialog {
    position: absolute;
    font-weight: normal;
    font-style: normal;
    font-size: 1rem;
    padding: 0;
    border-radius: var(--border-radius);
    color: inherit;
    background-color: var(--surface-900);
    border-width: 1px;
    border-style: solid;
    box-shadow: 0 0 1em rgba(0, 0, 0, 0.5);
    overflow-x: hidden;
    overflow-y: auto;
    
    &.primary {
      border-color: var(--primary-500);
    }
    
    &.secondary {
      border-color: var(--secondary-500);
    }

    &.warning {
      border-color: var(--warning-500);
    }

    &.error {
      border-color: var(--error-500);
    }

    .heading {
      position: absolute;
      left: 2rem;
      top: 2rem;
      margin: 0;
      padding: 0;
      display: flex;
      align-items: center;
      gap: 0.5rem;
      font-size: 1em;
    }
    
    .modal-content {
      display: flex;
      flex-direction: column;
      gap: 1em;
      padding: 2em;
      padding-top: 5em;
      padding-bottom: 2em;
    }

    footer {
      display: flex;
      justify-content: flex-end;
      bottom: 0;
      left: 0;
      right: 0;
      padding-bottom: 2em;
      padding-right: 2em;
      padding-left: 2em;
    }

    &::backdrop {
      backdrop-filter: blur(4px);
      background-color: rgba(0, 0, 0, 0.5);
    }
  }
</style>
