// packages/app/src/components/Row.tsx
import type { FlowComponent } from 'solid-js';
import { twMerge } from 'tailwind-merge';

interface Props {
  className?: string;
}

export const Row: FlowComponent<Props> = ({ children, className, ...rest }) => (
  <div {...rest} class={twMerge('flex flex-row flex-wrap mb-4 gap-4', className)}>
    {children}
  </div>
);

// src/components/row.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    children: Snippet;
  }

  let { children }: Props = $props();
</script>

<div>
  {@render children()}
</div>

<style>
  div {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    margin-bottom: 1em;
    gap: 1em;
  }
</style>
