// src/components/row.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    children: Snippet;
  }

  let { children }: Props = $props();
</script>

<div>
  {@render children()}
</div>

<style>
  div {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    margin-bottom: 1em;
    gap: 1em;
  }
</style>

// src/components/Row.tsx
import { type FlowComponent, splitProps } from 'solid-js';
import { twMerge } from 'tailwind-merge';

interface Props {
  class?: string;
}

export const Row: FlowComponent<Props> = (allProps) => {
  const [props, rest] = splitProps(allProps, ['children', 'class']);

  return (
    <div {...rest} class={twMerge('flex flex-row flex-wrap mb-4 gap-4', props.class)}>
      {props.children}
    </div>
  );
};
