// src/components/section.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    variant?: "primary" | "secondary" | "surface" | "inactive";
    children: Snippet;
  }

  let { children, variant = "primary" }: Props = $props();

  const className = $derived(`background-${variant}`);
</script>

<section class={className}>{@render children()}</section>

<style>
  section {
    display: flex;
    flex-direction: column;
    row-gap: 1em;
    margin-bottom: 1em;
    padding: 1em;
    border-radius: var(--border-radius);
  }

  .background-primary {
    background-color: var(--primary-800);
  }

  .background-secondary {
    background-color: var(--secondary-800);
  }

  .background-surface {
    background-color: var(--surface-800);
  }

  .background-inactive {
    background-color: var(--surface-400);
  }
</style>

// src/components/Section.tsx
import type { FlowComponent } from 'solid-js';
import { styled } from 'solid-styled-components';

export enum SectionVariant {
  PRIMARY = 0,
  SECONDARY = 1,
  SURFACE = 2,
  INACTIVE = 3,
}

export interface Props {
  variant?: SectionVariant;
}

export const Section: FlowComponent<Props> = ({ variant = SectionVariant.PRIMARY, children }) => (
  <StyledSection $variant={variant}>{children}</StyledSection>
);

interface StyledSectionProps {
  $variant: SectionVariant;
}

const StyledSection = styled.section<StyledSectionProps>`
  display: flex;
  flex-direction: column;
  row-gap: 1em;
  margin-bottom: 1em;
  padding: 1em;
  border-radius: var(--border-radius);
  background-color: ${({ $variant }) => backgroundColor($variant)};
`;

const backgroundColor = (variant: SectionVariant) => {
  switch (variant) {
    case SectionVariant.PRIMARY:
      return 'var(--primary-800)';
    case SectionVariant.SECONDARY:
      return 'var(--secondary-800)';
    case SectionVariant.SURFACE:
      return 'var(--surface-800)';
    case SectionVariant.INACTIVE:
      return 'var(--surface-400)';
  }
};
