// src/components/upload-button.svelte
<script lang="ts">
  import type { ChangeEventHandler } from "svelte/elements";
  import UploadMultipleIcon from "virtual:icons/mdi/upload-multiple";
  import { parseCsvFiles } from "@app/lib/csv";
  import type { CsvFile } from "@app/lib/csv";
  import Button from "@app/components/button.svelte";

  type OnFiles = (files: CsvFile[]) => void;

  interface Props {
    onFiles: OnFiles;
  }

  let { onFiles }: Props = $props();

  let inputElement: HTMLInputElement;

  const onChangeHandler: ChangeEventHandler<HTMLInputElement> = async (
    event,
  ): Promise<void> => {
    const { files } = event.currentTarget;

    if (files === null) {
      return;
    }

    onFiles(await parseCsvFiles(files));
  };
</script>

<input
  bind:this={inputElement}
  type="file"
  accept=".csv"
  multiple
  onchange={onChangeHandler}
/>
<Button onclick={() => inputElement.click()} variant="secondary" icon={uploadIcon}>
  Last opp
</Button>

{#snippet uploadIcon()}
  <UploadMultipleIcon />
{/snippet}

<style>
  input {
    display: none;
  }
</style>

// src/components/UploadButton.tsx
import { Button, ButtonVariant } from '@app/components/Button';
import { type CsvFile, parseCsvFiles } from '@app/lib/csv';
import { onCleanup, type VoidComponent } from 'solid-js';
import UploadMultipleIcon from '~icons/mdi/upload-multiple';

interface Props {
  onFiles: (files: CsvFile[]) => void;
}

export const UploadButton: VoidComponent<Props> = (props) => {
  const inputElement = document.createElement('input');
  inputElement.type = 'file';
  inputElement.accept = '.csv';
  inputElement.multiple = true;

  const onChangeHandler = async (): Promise<void> => {
    const { files } = inputElement;

    if (files !== null) {
      props.onFiles(await parseCsvFiles(files));
    }
  };

  inputElement.addEventListener('change', onChangeHandler);

  onCleanup(() => {
    inputElement.removeEventListener('change', onChangeHandler);
  });

  return (
    <Button onClick={() => inputElement.click()} variant={ButtonVariant.SECONDARY} icon={<UploadMultipleIcon />}>
      Last opp
    </Button>
  );
};
