// src/components/nordnet/nordnet-row.svelte
<script lang="ts">
  interface Props {
    line: string[];
    lineNumber: number;
  }

  let { line, lineNumber }: Props = $props();
</script>

<tr>
  <td>{lineNumber + 1}</td>
  {#each line as column}
    <td>{column}</td>
  {/each}
</tr>

<style>
  tr {
    &:nth-of-type(odd) {
      background-color: var(--table-odd-row);
    }

    &:nth-of-type(even) {
      background-color: var(--table-even-row);
    }

    &:hover {
      background-color: var(--table-hover-row);
    }
  }

  td {
    padding: 0.5em;
    white-space: nowrap;
  }
</style>

// packages/app/src/components/Nordnet/NordnetRow.tsx
import { type Accessor, Index, type VoidComponent } from 'solid-js';

interface Props {
  line: Accessor<string[]>;
  lineNumber: number;
}

export const NordnetRow: VoidComponent<Props> = ({ line, lineNumber }) => (
  <tr class="odd:bg-table-odd-row even:bg-table-even-row hover:bg-table-hover-row">
    <td class="p-2 whitespace-nowrap">{lineNumber + 1}</td>
    <Index each={line()}>{(cell) => <td class="p-2 whitespace-nowrap">{cell()}</td>}</Index>
  </tr>
);
