// src/app.svelte
<script lang="ts">
  import AppContainer from "@app/components/app-container.svelte";
  import Heading from "@app/components/heading.svelte";
  import Button from "@app/components/button.svelte";
  import Row from "@app/components/row.svelte";
  import NordnetSection from "@app/components/nordnet/nordnet-section.svelte";
  import UploadButton from "@app/components/upload-button.svelte";
  import { toNordnetLines } from "@app/lib/nordnet/csv-to-nordnet-lines";
  import { toFikenLines, type FikenFile } from "@app/lib/fiken";
  import { downloadFikenMapMultipleCsv, downloadFikenMapSingleCsv } from "@app/lib/download";
  import DownloadIcon from "virtual:icons/mdi/download";
  import DownloadMultipleIcon from "virtual:icons/mdi/download-multiple";
  import type { CsvFile } from "@app/lib/csv";
  import FikenSection from "@app/components/fiken/fiken-section.svelte";
  import { SvelteMap } from 'svelte/reactivity';

  let errorMessage = $state<string | null>(null);

  let csvFileMap = $state<SvelteMap<string, CsvFile>>(new SvelteMap());
  let fikenFiles = $state<FikenFile[]>([]);

  const setFiles = (files: CsvFile[]) => {
    for (const file of files) {
      csvFileMap.set(file.fileName, file);
    }
  };

  $effect(() => {
    const sortedCsvFiles = [...csvFileMap.values()].sort((a, b) => a.fileName.localeCompare(b.fileName));
    try {
      const nordnetLines = toNordnetLines(sortedCsvFiles);
      fikenFiles = toFikenLines(nordnetLines);
    } catch (e) {
      if (e instanceof Error) {
        errorMessage = e.message;
      } else {
        errorMessage = "Ukjent feil";
      }
    }
  });
</script>

<AppContainer onFiles={setFiles}>
  <header class="header">
    <Heading level={1} size="large" centered>Nordnet til Fiken</Heading>
    <p class="description">Konverter CSV eksportert fra Nordnet til et format Fiken forstår.</p>
  </header>
  
  <section>
    <Heading level={1} size="small" spacing>Nordnet</Heading>
  
    <Row>
      <UploadButton onFiles={setFiles} />
      {#if csvFileMap.size !== 0}
        <Button variant="error" icon={deleteAllIcon} onclick={() => csvFileMap.clear()}>Slett alle</Button>
      {/if}
    </Row>
  
    {#if csvFileMap.size === 0}
      <p>
        <em>
          Dra og slipp CSV-filer fra Nordnet hvor som helst for å få de oversatt
          til et format Fiken forstår.
        </em>
      </p>
    {:else}
      {#each csvFileMap as [fileName, { data }]}
        <NordnetSection {fileName} {data} onDelete={() => csvFileMap.delete(fileName)} />
      {/each}
    {/if}
  </section>

  {#if errorMessage !== null}
    <section>
      <Heading level={1} size="small" spacing>Feil</Heading>
      <p class="error-messages">{errorMessage}</p>
    </section>
  {/if}

  {#if fikenFiles.length !== 0}
    <section>
      <Heading level={1} size="small" spacing>Fiken</Heading>
  
      {#each fikenFiles as fikenFile}
        <FikenSection {...fikenFile} />
      {/each}

      <Row>
        <Button onclick={() => downloadFikenMapSingleCsv(fikenFiles.flatMap((f) => f.rows))} variant="primary" size="large" icon={downloadIcon}>
          Last ned alle - én fil
        </Button>
        <Button onclick={() => downloadFikenMapMultipleCsv(fikenFiles)} variant="primary" size="large" icon={downloadMultipleIcon}>
          Last ned alle - én fil per måned
        </Button>
      </Row>
    </section>
  {/if}

</AppContainer>

{#snippet downloadIcon()}
  <DownloadIcon  />
{/snippet}

{#snippet downloadMultipleIcon()}
  <DownloadMultipleIcon  />
{/snippet}

{#snippet deleteAllIcon()}
  <DownloadMultipleIcon  />
{/snippet}

<style>
  .header {
    display: flex;
    flex-direction: column;
    margin-bottom: 2em;
  }

  .description {
    margin: 0;
    font-style: italic;
    text-align: center;
  }

  .error-messages {
    white-space: pre;
  }
</style>

// src/App.tsx
import { AppFooter } from '@app/components/AppFooter';
import { Button, ButtonVariant } from '@app/components/Button';
import { DropZone } from '@app/components/DropZone';
import { FikenSection } from '@app/components/Fiken/FikenSection';
import { Header } from '@app/components/Header';
import { Heading, HeadingSize } from '@app/components/Heading';
import { NordnetSection } from '@app/components/Nordnet/NordnetSection';
import { Row } from '@app/components/Row';
import { UploadButton } from '@app/components/UploadButton';
import type { CsvFile } from '@app/lib/csv';
import { For, Show, type VoidComponent, createSignal } from 'solid-js';
import DeleteAllIcon from '~icons/mdi/delete-sweep';

export const App: VoidComponent = () => {
  const [csvFileList, setCsvFileList] = createSignal<CsvFile[]>([]);

  const removeFile = (fileName: string) => setCsvFileList(csvFileList().filter((file) => file.fileName !== fileName));

  const addFiles = (files: CsvFile[]) => {
    const previousFileList = csvFileList();
    const newFileList = [...previousFileList.filter((e) => !files.some((n) => n.fileName === e.fileName)), ...files];

    umami.track('Files added', {
      addedFileCount: files.length,
      adddedRowCount: files.reduce((acc, file) => acc + file.data.rows.length, 0),
      newFileCount: newFileList.length,
      newRowCount: newFileList.reduce((acc, file) => acc + file.data.rows.length, 0),
      previousFileCount: previousFileList.length,
      previousRowCount: previousFileList.reduce((acc, file) => acc + file.data.rows.length, 0),
    });

    setCsvFileList(newFileList);
  };

  const clearFiles = () => setCsvFileList([]);

  const hasFiles = () => csvFileList().length !== 0;

  return (
    <DropZone onFiles={addFiles}>
      <Header className="pt-4 px-4" spacing>
        <Heading level={1} size={HeadingSize.LARGE} centered>
          Nordnet til Fiken
        </Heading>

        <p class="m-0 italic text-center">Konverter CSV eksportert fra Nordnet til et format Fiken forstår.</p>
      </Header>

      <main class="flex flex-col gap-y-8 grow px-4 pb-16">
        <section>
          <Heading level={1} size={HeadingSize.SMALL} spacing>
            Nordnet
          </Heading>

          <Row>
            <UploadButton onFiles={addFiles} />

            <Show when={hasFiles()}>
              <Button variant={ButtonVariant.ERROR} icon={<DeleteAllIcon />} onClick={clearFiles}>
                Slett alle
              </Button>
            </Show>
          </Row>

          <Show when={!hasFiles()}>
            <p class="m-0 italic">Dra og slipp CSV-filer fra Nordnet hvor som helst.</p>
          </Show>

          <Show when={hasFiles()}>
            <div class="flex flex-col gap-y-4">
              <For each={csvFileList()}>
                {({ fileName, data }) => (
                  <NordnetSection fileName={fileName} data={data} onDelete={() => removeFile(fileName)} />
                )}
              </For>
            </div>
          </Show>
        </section>

        <FikenSection csvFiles={csvFileList} />
      </main>

      <AppFooter />
    </DropZone>
  );
};
